import PageBaseLayout from '@/components/layout/PageBaseLayout/PageBaseLayout';
import Head from 'next/head'
import Link from 'next/link';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Pup copy | Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageBaseLayout>
        <h1>Index page</h1>

        <Link href="login">To login page</Link>

        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt sint facilis velit, similique ratione excepturi adipisci natus mollitia dicta eveniet sapiente hic consectetur placeat numquam quaerat praesentium temporibus, iusto saepe.</p>
      </PageBaseLayout>
    </>
  )
}

export default HomePage;
