import PageBaseLayout from '@/components/layout/PageBaseLayout/PageBaseLayout';
import Head from 'next/head'
import Link from 'next/link';

const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Pup copy | Login page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageBaseLayout header={false} aside={false} footer={false}>
        <h1>Login page</h1>

        <Link href="/">To home page</Link>
      </PageBaseLayout>
    </>
  )
}

export default LoginPage;
